### ISSUE TITLE
UserWarning: resource_tracker:

### ISSUE THREAD

**Issue by yangboz** [Otman404/local-rag-llamaindex#2]
first off , thanks for your great work on it,  when I am verifying it on my local env[3.5.2 (22G91), python3.9]
and  running 'python rag/data.py --query "LLM" --max 5 --ingest '

it throws  as following:
···
UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
···

any idea? thanks.

**Comment by yangboz** [comment]
then  results to another issue as following :
```
  File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 96, in send
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
obj.result.config.optimizer_config.max_optimization_threads
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/int_type
```
any idea? thanks.

**Comment by QUEAHREN** [comment]
> then results to another issue as following : 然后导致另一个问题如下：
> 
> ```
>   File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 74, in request
>     return self.send(request, type_)
>   File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 96, in send
>     raise ResponseHandlingException(e)
> qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
> obj.result.config.optimizer_config.max_optimization_threads
>   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.5/v/int_type
> ```
> 
> any idea? thanks. 有什么想法吗？谢谢。

Do you solve this problem?

**Comment by yangboz** [comment]
> > then results to another issue as following : 然后导致另一个问题如下：
> > ```
> >   File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 74, in request
> >     return self.send(request, type_)
> >   File "/home/oem/anaconda3/envs/py39/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 96, in send
> >     raise ResponseHandlingException(e)
> > qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
> > obj.result.config.optimizer_config.max_optimization_threads
> >   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
> >     For further information visit https://errors.pydantic.dev/2.5/v/int_type
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > any idea? thanks. 有什么想法吗？谢谢。
> 
> Do you solve this problem?

warning可以忽略，问题发生在qdrant进入了非法字符，可能是中文字符没有实现CJKTokenizer，目前你可以通过pip instal chardet’解决初步的特殊字符码处理，最终还是要有CJK tokenizer支持。我一直在追问他们，反应很慢，罢了，换chromaDB了。
